### ISSUE TITLE
Passing a String to find_institution doesn't throw an # raises FDIC::Exceptions::RecordNotFound error

### ISSUE THREAD

**Issue by jhirbour** [ContinuityControl/fdic#6]
If you pass a string or a long number (10 digits) into find_institution you don't get a FDIC::Exceptions::RecordNotFound exception like the README states.

```
FDIC::BankFind.find_institution("DOG")
JSON::ParserError: 795: unexpected token at '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Draft//EN">
<HTML>
<HEAD>
<TITLE>Error 500--Internal Server Error</TITLE>
#
FDIC::BankFind.find_institution(6666666666)
JSON::ParserError: 795: unexpected token at '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Draft//EN">
```

**Comment by treznick** [comment]
hrm... I'll look into this

**Comment by danbernier** [comment]
Maybe because the FDIC bonks on it? That number will overflow a 32-bit int,
which is probably how they're storing keys...

On Wed, Nov 11, 2015 at 5:41 PM, Tom Reznick <notifications@github.com>
wrote:

> hrm... I'll look into this
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ContinuityControl/fdic/issues/6#issuecomment-155932234>
> .
>

-- 


-- 

------------------------------
This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity.
